import Head from "next/head";

import { SoloStrategyGameComponent } from "@/game/component/SoloStrategyGame";

// ********************************************************************************
export default function Home() {
  return (
    <>
      <Head>
        <title>Dilema del Prisionero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SoloStrategyGameComponent />
      </main>
    </>
  );
}
